apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: vps-custom-jenkins
    name: vps-custom-jenkins
  spec:
    replicas: 1
    selector:
      app: vps-custom-jenkins
      deploymentconfig: vps-custom-jenkins
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.jenkins.image.entrypoint: '["/usr/bin/bash"]'
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: vps-custom-jenkins
          deploymentconfig: vps-custom-jenkins
      spec:
        containers:
        - image: 172.30.133.175:5000/jenkins/jenkins@sha256:323c1c6ad7e2a45310a2c290fa071d432770e8540ec9de82ac0a670625a46797
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vps-custom-jenkins
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: vps-custom-jenkins:latest
  status:
    details:
      causes:
      - imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: vps-custom-jenkins:latest
kind: List
metadata: {}
