apiVersion: v1
kind: BuildConfig
metadata:
  name: vps-custom-jenkins-build
spec:
  source:                       
    git:
      uri: git@github4.vps.no:infra/vps-custom-jenkins.git
    sourceSecret:
      name: "sshsecret"
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: vps-custom-jenkins:latest
